### ISSUE TITLE
Color Styling Audio Player

### ISSUE THREAD

**Issue by Colhodm** [slash9494/react-modern-audio-player#4]
Hey,

This library is incredible and the API is very thoughtfully constructed, but the documentation on how to style the colors/other aesthetic properties are very lacking.

Could you include an example, where you change the border radius/background color of an item?

**Comment by Colhodm** [comment]
Ok closing this issue, because I figured it out, but took a lot of digging and assumed general familiarity with Adobe Spectrum which is not super popular.

The way to do any custom styling on the component is to pass a prop into Root Props with an UNSAFE_className of whatever you want. Then in your css style sheet, style this. For example:

in your CSS:
.rm-audio-player-provider {
  --rm-audio-player-interface-container: yellow;
  --rm-audio-player-progress-bar-background: red;
  --rm-audio-player-progress-bar:#000000;
}

in your JSX:
rootContainerProps={{
            colorScheme: theme,
            width,
            UNSAFE_className: "rm-audio-player-provider"
          }}

Heavily encourage the project owner to better document this use case.

**Comment by slash9494** [comment]
I intended users to customize colors by root classname `rm-audio-player-provider` or `rootContainerProps` 
So the example that you show above is what I fully intend to do.
But if you couldn't fully understand how to style the colors by just `override style` section in the document,
I will consider updating the document detailedly
